"""Creating models again

Revision ID: 5d42a0c65360
Revises: 
Create Date: 2025-12-18 01:58:48.409359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d42a0c65360'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('trade_regime', sa.Enum('FREE_TRADE', 'MOST_FAVORED', 'GENERAL', name='traderegimetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=False)
    op.create_index(op.f('ix_countries_name_ru'), 'countries', ['name_ru'], unique=True)
    op.create_table('tn_ved_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_util_applicable', sa.Boolean(), nullable=False),
    sa.Column('calc_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tn_ved_codes_code'), 'tn_ved_codes', ['code'], unique=True)
    op.create_index(op.f('ix_tn_ved_codes_is_util_applicable'), 'tn_ved_codes', ['is_util_applicable'], unique=False)
    op.create_index(op.f('ix_tn_ved_codes_parent_code'), 'tn_ved_codes', ['parent_code'], unique=False)
    op.create_table('tariff_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tn_ved_code_id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.Enum('AD_VALOREM', 'SPECIFIC', 'MIXED', 'COMBINED', name='ratetype'), nullable=False),
    sa.Column('ad_valorem_rate', sa.Float(), nullable=False),
    sa.Column('specific_rate', sa.Float(), nullable=True),
    sa.Column('specific_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specific_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('excise_type', sa.Enum('AD_VALOREM', 'SPECIFIC', 'MIXED', 'COMBINED', name='excisetype'), nullable=False),
    sa.Column('excise_ad_valorem_rate', sa.Float(), nullable=False),
    sa.Column('excise_specific_rate', sa.Float(), nullable=True),
    sa.Column('excise_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excise_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tn_ved_code_id'], ['tn_ved_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_rates_tn_ved_code_id'), 'tariff_rates', ['tn_ved_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_rates_tn_ved_code_id'), table_name='tariff_rates')
    op.drop_table('tariff_rates')
    op.drop_index(op.f('ix_tn_ved_codes_parent_code'), table_name='tn_ved_codes')
    op.drop_index(op.f('ix_tn_ved_codes_is_util_applicable'), table_name='tn_ved_codes')
    op.drop_index(op.f('ix_tn_ved_codes_code'), table_name='tn_ved_codes')
    op.drop_table('tn_ved_codes')
    op.drop_index(op.f('ix_countries_name_ru'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
